import {
  StockItem,
  Instructor,
  ClassGroup,
  Recipe,
  Requisition,
  DispatchRecord,
  KitchenUtensil,
  InstructorPermissionSettings,
  ProcurementCycleInfo,
  AcademicLessonSchedule,
} from './types';

export const initialPermissionSettings: InstructorPermissionSettings = {
  allowAlterationsWithoutNotice: false,
  requireAdminApproval: true,
  maxNoticeHours: 12,
  allowExtraUtensilsCheckout: true,
  allowEmergencyScheduleSwap: false,
};

export const initialUtensils: KitchenUtensil[] = [
  // 1. Corte & Facas
  {
    id: 'ut-1',
    code: 'UT-FAC-01',
    name: 'Faca do Chef 8" em Aço Alemão Forjado',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 24,
    maintenanceStatus: 'pronto',
    description: 'Fio navalha profissional com fio liso para cortes precisos.',
  },
  {
    id: 'ut-2',
    code: 'UT-FAC-02',
    name: 'Faca de Tornear / Legumes 3.5"',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 20,
    maintenanceStatus: 'pronto',
    description: 'Lâmina curva para esculpir e tornear vegetais.',
  },
  {
    id: 'ut-3',
    code: 'UT-FAC-03',
    name: 'Faca de Desossar e Filetear Flexível 6"',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 15,
    maintenanceStatus: 'pronto',
    description: 'Flexibilidade ideal para limpeza de carnes, aves e peixes.',
  },
  {
    id: 'ut-4',
    code: 'UT-FAC-04',
    name: 'Faca Serrilhada para Pães e Folhados 10"',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 16,
    maintenanceStatus: 'pronto',
    description: 'Dentes afiados para fatiar crostas sem amassar o miolo.',
  },
  {
    id: 'ut-5',
    code: 'UT-COR-01',
    name: 'Mandoline Profissional com Lâminas Julienne Regulável',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 8,
    maintenanceStatus: 'pronto',
    description: 'Cortes milimétricos com protetor de dedos e espessura ajustável.',
  },
  {
    id: 'ut-6',
    code: 'UT-COR-02',
    name: 'Descascador de Legumes Giratório em Inox (tipo Y)',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 30,
    maintenanceStatus: 'pronto',
    description: 'Ergonômico de alta durabilidade.',
  },
  {
    id: 'ut-7',
    code: 'UT-COR-03',
    name: 'Tesoura Culinária Reforçada Desmontável',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 12,
    maintenanceStatus: 'pronto',
    description: 'Corte de aves, barbatanas e ervas com fácil higienização.',
  },
  {
    id: 'ut-8',
    code: 'UT-AFI-01',
    name: 'Chaira Estriada de Afiação e Alinhamento 12"',
    category: 'Corte & Facas',
    unit: 'un',
    totalAvailable: 14,
    maintenanceStatus: 'pronto',
    description: 'Aço cromo vanádio com revestimento duro.',
  },

  // 2. Apoio, Tábuas & Higiene
  {
    id: 'ut-9',
    code: 'UT-TAB-01',
    name: 'Kit de Tábuas de Corte Coloridas HACCP (5 cores)',
    category: 'Apoio, Tábuas & Higiene',
    unit: 'kit',
    totalAvailable: 18,
    maintenanceStatus: 'pronto',
    description: 'Norma sanitária: branca, vermelha, azul, verde e amarela.',
  },
  {
    id: 'ut-10',
    code: 'UT-TAB-02',
    name: 'Tábua de Corte Polietileno Branca 50x30cm (Panificação/Laticínios)',
    category: 'Apoio, Tábuas & Higiene',
    unit: 'un',
    totalAvailable: 25,
    maintenanceStatus: 'pronto',
    description: 'Polietileno de alta densidade atóxico.',
  },
  {
    id: 'ut-11',
    code: 'UT-TAB-03',
    name: 'Tábua de Corte Polietileno Vermelha 50x30cm (Carnes Vermelhas)',
    category: 'Apoio, Tábuas & Higiene',
    unit: 'un',
    totalAvailable: 20,
    maintenanceStatus: 'pronto',
    description: 'Canaleta coletora de sucos.',
  },
  {
    id: 'ut-12',
    code: 'UT-HIG-01',
    name: 'Panos de Prato Profissionais 100% Algodão (Kit com 6)',
    category: 'Apoio, Tábuas & Higiene',
    unit: 'kit',
    totalAvailable: 40,
    maintenanceStatus: 'pronto',
    description: 'Alta absorção sem soltar fiapos.',
  },
  {
    id: 'ut-13',
    code: 'UT-HIG-02',
    name: 'Luvas Térmicas de Silicone para Forno Combinado (Par)',
    category: 'Apoio, Tábuas & Higiene',
    unit: 'par',
    totalAvailable: 10,
    maintenanceStatus: 'pronto',
    description: 'Resistência até 300°C com pegada antiderrapante.',
  },

  // 3. Confeitaria & Panificação
  {
    id: 'ut-14',
    code: 'UT-CONF-01',
    name: 'Fouet / Batedor de Arame em Aço Inox 30cm',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 28,
    maintenanceStatus: 'pronto',
    description: 'Fios reforçados e vedação higiênica no cabo.',
  },
  {
    id: 'ut-15',
    code: 'UT-CONF-02',
    name: 'Espátula de Silicone Pão-Duro (Resistente a 260°C)',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 35,
    maintenanceStatus: 'pronto',
    description: 'Silicone inteiriço sem emendas, flexível e atóxico.',
  },
  {
    id: 'ut-16',
    code: 'UT-CONF-03',
    name: 'Espátula Reta e Degrau de Confeiteiro em Inox 25cm',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 18,
    maintenanceStatus: 'pronto',
    description: 'Alisamento perfeito para bolos e placas de chocolate.',
  },
  {
    id: 'ut-17',
    code: 'UT-PAN-01',
    name: 'Rolo de Polietileno Antiaderente para Massas 40cm',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 15,
    maintenanceStatus: 'pronto',
    description: 'Superfície lisa para abrir massas de levain e folhados.',
  },
  {
    id: 'ut-18',
    code: 'UT-PAN-02',
    name: 'Tapete de Silicone Silpat Antiaderente 40x30cm',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 22,
    maintenanceStatus: 'pronto',
    description: 'Fibra de vidro siliconada para assar sem untar.',
  },
  {
    id: 'ut-19',
    code: 'UT-CONF-04',
    name: 'Jogo de Aros Cortadores Redondos em Inox (12 tamanhos)',
    category: 'Confeitaria & Panificação',
    unit: 'cj',
    totalAvailable: 12,
    maintenanceStatus: 'pronto',
    description: 'Aço inox com estojo protetor.',
  },
  {
    id: 'ut-20',
    code: 'UT-CONF-05',
    name: 'Maçarico Culinário a Gás com Acendimento Automático',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 8,
    maintenanceStatus: 'pronto',
    description: 'Chama ajustável para dourar merengues e gratinados.',
  },
  {
    id: 'ut-21',
    code: 'UT-CONF-06',
    name: 'Saco de Confeitar com Kit de Bicos Inox (12 peças)',
    category: 'Confeitaria & Panificação',
    unit: 'kit',
    totalAvailable: 20,
    maintenanceStatus: 'pronto',
    description: 'Bicos perlê, pitanga, folha e flor.',
  },
  {
    id: 'ut-22',
    code: 'UT-CONF-07',
    name: 'Peneira Culinária Tamis em Aço Inox 25cm',
    category: 'Confeitaria & Panificação',
    unit: 'un',
    totalAvailable: 16,
    maintenanceStatus: 'pronto',
    description: 'Malha ultrafina para arejar farinhas e polvilhar cacau.',
  },

  // 4. Panelas & Formas
  {
    id: 'ut-23',
    code: 'UT-PAN-01',
    name: 'Panela Caçarola Inox Fundo Triplo 20cm (3.5L)',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 22,
    maintenanceStatus: 'pronto',
    description: 'Distribuição térmica uniforme sem pontos de queima.',
  },
  {
    id: 'ut-24',
    code: 'UT-PAN-02',
    name: 'Frigideira Profissional Antiaderente 28cm Fundo Triplo',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 20,
    maintenanceStatus: 'pronto',
    description: 'Revestimento cerâmico reforçado para salteados.',
  },
  {
    id: 'ut-25',
    code: 'UT-PAN-03',
    name: 'Wok Oriental em Aço Carbono 32cm com Cabo de Madeira',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 6,
    maintenanceStatus: 'pronto',
    description: 'Alta temperatura para salteados rápidos.',
  },
  {
    id: 'ut-26',
    code: 'UT-GN-01',
    name: 'Cuba Gastronorm GN 1/1 Inox com Tampa (65mm)',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 16,
    maintenanceStatus: 'pronto',
    description: 'Padrão gastronorm para armazenamento e forno combinado.',
  },
  {
    id: 'ut-27',
    code: 'UT-GN-02',
    name: 'Cuba Gastronorm GN 1/2 Inox com Tampa (65mm)',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 24,
    maintenanceStatus: 'pronto',
    description: 'Ideal para mise en place intermediária.',
  },
  {
    id: 'ut-28',
    code: 'UT-FOR-01',
    name: 'Assadeira Perfurada em Alumínio para Forno 60x40cm',
    category: 'Panelas & Formas',
    unit: 'un',
    totalAvailable: 30,
    maintenanceStatus: 'pronto',
    description: 'Circulação de ar uniforme para pães e massas.',
  },
  {
    id: 'ut-29',
    code: 'UT-BOW-01',
    name: 'Jogo de Bowls / Tigelas de Aço Inox (P, M, G - 3 peças)',
    category: 'Panelas & Formas',
    unit: 'cj',
    totalAvailable: 26,
    maintenanceStatus: 'pronto',
    description: 'Base arredondada para bater e misturar ingredientes.',
  },

  // 5. Eletroportáteis & Motores
  {
    id: 'ut-30',
    code: 'UT-ELET-01',
    name: 'Batedeira Planetária 5L com 3 Batedores (Globo, Raquete, Gancho)',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 10,
    maintenanceStatus: 'pronto',
    description: 'Motor potente para massas pesadas e claras em neve.',
  },
  {
    id: 'ut-31',
    code: 'UT-ELET-02',
    name: 'Processador de Alimentos / Cutter Industrial 4L',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 5,
    maintenanceStatus: 'pronto',
    description: 'Picar, emulsificar e triturar em segundos.',
  },
  {
    id: 'ut-32',
    code: 'UT-ELET-03',
    name: 'Mixer de Imersão Profissional com Braço Longo 35cm',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 8,
    maintenanceStatus: 'pronto',
    description: 'Emulsões finas de molhos diretamente na panela.',
  },
  {
    id: 'ut-33',
    code: 'UT-ELET-04',
    name: 'Liquidificador Industrial de Alta Rotação 2L Inox',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 7,
    maintenanceStatus: 'pronto',
    description: '25.000 RPM para purês sedosos e cremes lisos.',
  },
  {
    id: 'ut-34',
    code: 'UT-ELET-05',
    name: 'Seladora a Vácuo de Bancada Profissional',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 3,
    maintenanceStatus: 'pronto',
    description: 'Controle de pressão e tempo de vácuo.',
  },
  {
    id: 'ut-35',
    code: 'UT-ELET-06',
    name: 'Termocirculador de Precisão Sous-Vide Digital',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 4,
    maintenanceStatus: 'pronto',
    description: 'Cocção de baixas temperaturas com estabilidade ±0.1°C.',
  },
  {
    id: 'ut-36',
    code: 'UT-ELET-07',
    name: 'Cilindro Laminador Manual de Massas Frescas Inox',
    category: 'Eletroportáteis & Motores',
    unit: 'un',
    totalAvailable: 8,
    maintenanceStatus: 'pronto',
    description: 'Regulagem de espessura de 0.5mm a 5mm.',
  },

  // 6. Medição & Precisão
  {
    id: 'ut-37',
    code: 'UT-MED-01',
    name: 'Balança Digital de Alta Precisão 0.1g a 3kg',
    category: 'Medição & Precisão',
    unit: 'un',
    totalAvailable: 24,
    maintenanceStatus: 'pronto',
    description: 'Função tara e visor iluminado para pesagem precisa.',
  },
  {
    id: 'ut-38',
    code: 'UT-MED-02',
    name: 'Termômetro Digital Culinário Tipo Espeto (-50°C a 300°C)',
    category: 'Medição & Precisão',
    unit: 'un',
    totalAvailable: 26,
    maintenanceStatus: 'pronto',
    description: 'Leitura instantânea para carnes, caldas e chocolates.',
  },
  {
    id: 'ut-39',
    code: 'UT-MED-03',
    name: 'Termômetro Infravermelho a Laser para Superfícies',
    category: 'Medição & Precisão',
    unit: 'un',
    totalAvailable: 6,
    maintenanceStatus: 'pronto',
    description: 'Medição sem contato de panelas, chapas e açúcares.',
  },
  {
    id: 'ut-40',
    code: 'UT-MED-04',
    name: 'Jarra Graduada Dosadora 1000ml em Policarbonato',
    category: 'Medição & Precisão',
    unit: 'un',
    totalAvailable: 30,
    maintenanceStatus: 'pronto',
    description: 'Escalas de ml, xícaras e onças.',
  },
  {
    id: 'ut-41',
    code: 'UT-MED-05',
    name: 'Colheres e Copos Medidores em Inox (Kit 8 peças)',
    category: 'Medição & Precisão',
    unit: 'kit',
    totalAvailable: 20,
    maintenanceStatus: 'pronto',
    description: 'Medidas padronizadas internacionais de colheres e xícaras.',
  },
  {
    id: 'ut-42',
    code: 'UT-MED-06',
    name: 'Timer / Cronômetro Digital Duplo de Bancada',
    category: 'Medição & Precisão',
    unit: 'un',
    totalAvailable: 15,
    maintenanceStatus: 'pronto',
    description: 'Alarme sonoro potente para controle de forno.',
  },
];

export const initialStockItems: StockItem[] = [
  {
    id: 'item-1',
    code: 'EST-001',
    name: 'Farinha de Trigo Especial 00',
    category: 'Secos e Farinhas',
    currentQuantity: 42,
    minQuantity: 15,
    unit: 'kg',
    location: 'Despensa Seca - Prateleira A1',
    expiryDate: '2026-12-10',
    costPerUnit: 6.8,
    updatedAt: '2026-09-14 09:30',
  },
  {
    id: 'item-2',
    code: 'EST-002',
    name: 'Manteiga Extra Sem Sal 82% Lipídios',
    category: 'Laticínios e Frios',
    currentQuantity: 14.5,
    minQuantity: 10,
    unit: 'kg',
    location: 'Câmara Fria Laticínios',
    expiryDate: '2026-10-25',
    costPerUnit: 34.0,
    updatedAt: '2026-09-14 08:45',
  },
  {
    id: 'item-3',
    code: 'EST-003',
    name: 'Açúcar Cristal Refinado',
    category: 'Secos e Farinhas',
    currentQuantity: 28,
    minQuantity: 12,
    unit: 'kg',
    location: 'Despensa Seca - Prateleira A2',
    expiryDate: '2027-03-01',
    costPerUnit: 4.5,
    updatedAt: '2026-09-12 11:20',
  },
  {
    id: 'item-4',
    code: 'EST-004',
    name: 'Ovos Caipiras Grandes (Dúzia)',
    category: 'Laticínios e Frios',
    currentQuantity: 8, // baixa quantidade para alertar
    minQuantity: 12,
    unit: 'cx',
    location: 'Geladeira 02 - Prateleira Média',
    expiryDate: '2026-09-30',
    costPerUnit: 14.0,
    updatedAt: '2026-09-15 07:10',
  },
  {
    id: 'item-5',
    code: 'EST-005',
    name: 'Chocolate Nobre Meio Amargo 54% Callebaut',
    category: 'Confeitaria e Chocolates',
    currentQuantity: 18,
    minQuantity: 8,
    unit: 'kg',
    location: 'Armário Climatizado Chocolate',
    expiryDate: '2027-01-15',
    costPerUnit: 65.0,
    updatedAt: '2026-09-13 14:00',
  },
  {
    id: 'item-6',
    code: 'EST-006',
    name: 'Leite Integral UHT',
    category: 'Laticínios e Frios',
    currentQuantity: 36,
    minQuantity: 20,
    unit: 'L',
    location: 'Despensa Seca - Palete 03',
    expiryDate: '2026-11-18',
    costPerUnit: 5.2,
    updatedAt: '2026-09-14 16:30',
  },
  {
    id: 'item-7',
    code: 'EST-007',
    name: 'Azeite de Oliva Extra Virgem 0.2%',
    category: 'Óleos e Condimentos',
    currentQuantity: 12,
    minQuantity: 6,
    unit: 'L',
    location: 'Despensa Molhos & Óleos',
    expiryDate: '2027-05-10',
    costPerUnit: 48.0,
    updatedAt: '2026-09-10 10:15',
  },
  {
    id: 'item-8',
    code: 'EST-008',
    name: 'Arroz Carnaroli Especial Risoto',
    category: 'Secos e Farinhas',
    currentQuantity: 22,
    minQuantity: 10,
    unit: 'kg',
    location: 'Despensa Seca - Prateleira B1',
    expiryDate: '2027-02-20',
    costPerUnit: 22.5,
    updatedAt: '2026-09-11 13:00',
  },
  {
    id: 'item-9',
    code: 'EST-009',
    name: 'Queijo Parmigiano Reggiano D.O.P.',
    category: 'Laticínios e Frios',
    currentQuantity: 4.2,
    minQuantity: 5, // baixo estoque!
    unit: 'kg',
    location: 'Câmara Fria Queijos',
    expiryDate: '2026-10-15',
    costPerUnit: 140.0,
    updatedAt: '2026-09-14 17:00',
  },
  {
    id: 'item-10',
    code: 'EST-010',
    name: 'Cogumelos Paris Frescos',
    category: 'Hortifruti',
    currentQuantity: 6.5,
    minQuantity: 4,
    unit: 'kg',
    location: 'Câmara Fria Legumes',
    expiryDate: '2026-09-20',
    costPerUnit: 32.0,
    updatedAt: '2026-09-15 06:40',
  },
  {
    id: 'item-11',
    code: 'EST-011',
    name: 'Fermento Biológico Seco Instantâneo',
    category: 'Secos e Farinhas',
    currentQuantity: 9,
    minQuantity: 4,
    unit: 'pct',
    location: 'Despensa Seca - Prateleira A1',
    expiryDate: '2027-04-12',
    costPerUnit: 18.0,
    updatedAt: '2026-09-12 09:10',
  },
  {
    id: 'item-12',
    code: 'EST-012',
    name: 'Creme de Leite Fresco Pasteurizado 35%',
    category: 'Laticínios e Frios',
    currentQuantity: 15,
    minQuantity: 8,
    unit: 'L',
    location: 'Câmara Fria Laticínios',
    expiryDate: '2026-09-28',
    costPerUnit: 26.0,
    updatedAt: '2026-09-14 09:10',
  },
  {
    id: 'item-13',
    code: 'EST-013',
    name: 'Flor de Sal Gourmet',
    category: 'Óleos e Condimentos',
    currentQuantity: 3.5,
    minQuantity: 2,
    unit: 'kg',
    location: 'Armário Especiarias Finas',
    expiryDate: '2028-01-01',
    costPerUnit: 42.0,
    updatedAt: '2026-09-08 14:20',
  },
  {
    id: 'item-14',
    code: 'EST-014',
    name: 'Cebola Branca Selecionada',
    category: 'Hortifruti',
    currentQuantity: 25,
    minQuantity: 10,
    unit: 'kg',
    location: 'Despensa Ventilada Hortifruti',
    expiryDate: '2026-10-05',
    costPerUnit: 5.5,
    updatedAt: '2026-09-13 11:30',
  },
  {
    id: 'item-15',
    code: 'EST-015',
    name: 'Filé Mignon Bovino Limpo',
    category: 'Carnes e Pescados',
    currentQuantity: 12.0,
    minQuantity: 8,
    unit: 'kg',
    location: 'Câmara Fria Carnes',
    expiryDate: '2026-09-22',
    costPerUnit: 89.0,
    updatedAt: '2026-09-14 15:10',
  },
];

export const initialInstructors: Instructor[] = [
  {
    id: 'inst-1',
    registrationNumber: 'CHEF-001',
    name: 'Chef Bernardo Guimarães',
    email: 'bernardo.chef@sigec.culinaria.com',
    phone: '(11) 98765-4321',
    specialty: 'Panificação Clássica & Viennoiserie',
    color: '#002747',
    active: true,
    notes: 'Responsável técnico pelo laboratório de panificação e fornos de lastro.',
    createdAt: '2026-01-10',
  },
  {
    id: 'inst-2',
    registrationNumber: 'CHEF-002',
    name: 'Chef Helena Vasconcelos',
    email: 'helena.chef@sigec.culinaria.com',
    phone: '(11) 97654-3210',
    specialty: 'Confeitaria Fina Francesa & Chocolataria',
    color: '#ff8928',
    active: true,
    notes: 'Coordena o ateliê climatizado de pâtisserie e temperagem de chocolate.',
    createdAt: '2026-01-15',
  },
  {
    id: 'inst-3',
    registrationNumber: 'CHEF-003',
    name: 'Chef Rodrigo Martins',
    email: 'rodrigo.chef@sigec.culinaria.com',
    phone: '(11) 96543-2109',
    specialty: 'Cozinha Mediterrânea & Carnes Nobres',
    color: '#003660',
    active: true,
    notes: 'Gestão de bancadas de charcutaria, carnes nobres e cocções térmicas.',
    createdAt: '2026-02-01',
  },
  {
    id: 'inst-4',
    registrationNumber: 'CHEF-004',
    name: 'Chef Larissa Dias',
    email: 'larissa.chef@sigec.culinaria.com',
    phone: '(11) 95432-1098',
    specialty: 'Massas Artesanais & Molhos Clássicos',
    color: '#eb7717',
    active: true,
    notes: 'Especialista em sêmola, fermentação natural e culinária italiana contemporânea.',
    createdAt: '2026-02-12',
  },
];

export const initialClasses: ClassGroup[] = [
  {
    id: 'turma-1',
    code: 'TUR-2026-M1',
    name: 'Gastronomia Profissional M1',
    shift: 'Manhã',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    instructorId: 'inst-3',
    studentCount: 16,
    status: 'ativa',
    startDate: '2026-08-01',
    endDate: '2026-12-18',
    description: 'Turma em andamento com foco em gastronomia profissional clássica e contemporânea.',
  },
  {
    id: 'turma-2',
    code: 'TUR-2026-T1',
    name: 'Pâtisserie & Confeitaria Avançada',
    shift: 'Tarde',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    instructorId: 'inst-2',
    studentCount: 14,
    status: 'ativa',
    startDate: '2026-08-05',
    endDate: '2026-12-15',
    description: 'Especialização em chocolateria belga, temperagem e viennoiserie fina.',
  },
  {
    id: 'turma-3',
    code: 'TUR-2026-N1',
    name: 'Panificação Artesanal & Levain',
    shift: 'Noite',
    kitchenRoom: 'Laboratório de Panificação 02',
    instructorId: 'inst-1',
    studentCount: 18,
    status: 'ativa',
    startDate: '2026-08-10',
    endDate: '2026-12-20',
    description: 'Turma noturna de panificação de fermentação natural, fogaças e massas folhadas.',
  },
  {
    id: 'turma-4',
    code: 'TUR-2026-M2',
    name: 'Cozinha Italiana & Massas Frescas',
    shift: 'Manhã',
    kitchenRoom: 'Cozinha Prática 03',
    instructorId: 'inst-4',
    studentCount: 15,
    status: 'ativa',
    startDate: '2026-08-12',
    endDate: '2026-12-19',
    description: 'Práticas intensivas de sêmola, recheios finos e risotos mediterrâneos.',
  },
  {
    id: 'turma-5',
    code: 'TUR-2026-N0',
    name: 'Técnicas Básicas de Cocção & Habilidades de Faca (2026.1)',
    shift: 'Noite',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    instructorId: 'inst-3',
    studentCount: 16,
    status: 'inativa',
    startDate: '2026-02-15',
    endDate: '2026-07-10',
    description: 'Turma concluída no semestre anterior. Disponível para consulta histórica de consumo.',
  },
  {
    id: 'turma-6',
    code: 'TUR-2026-T0',
    name: 'Fundamentos de Confeitaria Clássica (2026.1)',
    shift: 'Tarde',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    instructorId: 'inst-2',
    studentCount: 12,
    status: 'inativa',
    startDate: '2026-02-20',
    endDate: '2026-07-15',
    description: 'Turma concluída no 1º semestre de 2026. Dados mantidos para relatórios analíticos.',
  },
];

export const initialRecipes: Recipe[] = [
  {
    id: 'rec-1',
    name: 'Croissant Francês Tradicional',
    category: 'Panificação & Massas Folhadas',
    yieldPortions: 24,
    prepTimeMinutes: 240,
    difficulty: 'Avançado',
    instructions: [
      'Misturar a farinha 00, açúcar, leite, fermento e sal na masseira até atingir ponto de véu.',
      'Descansar a massa na geladeira por 2 horas a 4°C.',
      'Abrir a massa em retângulo e aplicar o bloco de manteiga 82% fria no centro.',
      'Executar as dobras simples e duplas com intervalos de descanso refrigerado.',
      'Modelar os croissants, fermentar a 26°C por 90 minutos.',
      'Pincelar com ovo batido e assar a 190°C por 18 minutos.',
    ],
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 1.5, unit: 'kg' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 0.8, unit: 'kg' },
      { stockItemId: 'item-6', name: 'Leite Integral UHT', quantity: 0.7, unit: 'L' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 0.15, unit: 'kg' },
      { stockItemId: 'item-11', name: 'Fermento Biológico Seco Instantâneo', quantity: 0.05, unit: 'pct' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 0.5, unit: 'cx' },
    ],
  },
  {
    id: 'rec-2',
    name: 'Risoto de Cogumelos Paris e Parmigiano',
    category: 'Cozinha Quente & Risotos',
    yieldPortions: 12,
    prepTimeMinutes: 45,
    difficulty: 'Médio',
    instructions: [
      'Picar a cebola em brunoise fino e refogar no azeite até translúcida.',
      'Adicionar o arroz Carnaroli e nacarar por 2 minutos mexendo sempre.',
      'Saltear os cogumelos Paris separadamente na manteiga em fogo alto.',
      'Adicionar caldo aos poucos no arroz mantendo fervura branda.',
      'Finalizar mantecando com queijo Parmigiano Reggiano ralado e manteiga bem gelada.',
    ],
    ingredients: [
      { stockItemId: 'item-8', name: 'Arroz Carnaroli Especial Risoto', quantity: 1.2, unit: 'kg' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 1.5, unit: 'kg' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 0.4, unit: 'kg' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 0.3, unit: 'kg' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.2, unit: 'L' },
      { stockItemId: 'item-14', name: 'Cebola Branca Selecionada', quantity: 0.5, unit: 'kg' },
    ],
  },
  {
    id: 'rec-3',
    name: 'Entremet de Chocolate Belga 54%',
    category: 'Confeitaria & Chocolataria',
    yieldPortions: 16,
    prepTimeMinutes: 120,
    difficulty: 'Avançado',
    instructions: [
      'Preparar a base crocante com chocolate derretido.',
      'Bater o creme de leite fresco em ponto chantilly macio.',
      'Fazer ganache aveludada emulsionando com o chocolate 54%.',
      'Montar nos aros de inox e levar ao ultracongelador.',
      'Finalizar com glaçagem espelho brilhante a 32°C.',
    ],
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 1.2, unit: 'kg' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 1.5, unit: 'L' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 0.4, unit: 'kg' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 1.0, unit: 'cx' },
    ],
  },
  {
    id: 'rec-4',
    name: 'Focaccia Genovese com Alecrim & Flor de Sal',
    category: 'Panificação & Massas',
    yieldPortions: 20,
    prepTimeMinutes: 150,
    difficulty: 'Fácil',
    instructions: [
      'Hidratar a farinha 00 com 75% de água gelada.',
      'Fazer dobras de 30 em 30 minutos na bancada untada com azeite.',
      'Transferir para assadeira e realizar a salmoura aromática com azeite e flor de sal.',
      'Afundar os dedos criando alvéolos característicos e assar a 220°C até dourar.',
    ],
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 2.0, unit: 'kg' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.35, unit: 'L' },
      { stockItemId: 'item-11', name: 'Fermento Biológico Seco Instantâneo', quantity: 0.04, unit: 'pct' },
      { stockItemId: 'item-13', name: 'Flor de Sal Gourmet', quantity: 0.08, unit: 'kg' },
    ],
  },
];

export const initialRequisitions: Requisition[] = [
  {
    id: 'req-1',
    code: 'REQ-104',
    classId: 'turma-2',
    instructorId: 'inst-2',
    recipeId: 'rec-3',
    recipeName: 'Entremet de Chocolate Belga 54%',
    purpose: 'Aula Prática nº 8 - Técnicas de Emulsão, Cristalização e Glaçagem',
    requestDate: '2026-09-15 08:30',
    status: 'pendente', // Pendente para o usuário testar análise, aprovação e permissões!
    items: [
      {
        stockItemId: 'item-5',
        name: 'Chocolate Nobre Meio Amargo 54% Callebaut',
        requestedQuantity: 2.5,
        approvedQuantity: 2.5,
        unit: 'kg',
      },
      {
        stockItemId: 'item-12',
        name: 'Creme de Leite Fresco Pasteurizado 35%',
        requestedQuantity: 3.0,
        approvedQuantity: 3.0,
        unit: 'L',
      },
      {
        stockItemId: 'item-3',
        name: 'Açúcar Cristal Refinado',
        requestedQuantity: 1.0,
        approvedQuantity: 1.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-4',
        name: 'Ovos Caipiras Grandes (Dúzia)',
        requestedQuantity: 2.0,
        approvedQuantity: 2.0,
        unit: 'cx',
      },
    ],
    utensils: [
      {
        utensilId: 'ut-14',
        name: 'Fouet / Batedor de Arame em Aço Inox 30cm',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 2,
        approvedQuantity: 2,
        unit: 'un',
      },
      {
        utensilId: 'ut-15',
        name: 'Espátula de Silicone Pão-Duro (Resistente a 260°C)',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 4,
        approvedQuantity: 4,
        unit: 'un',
      },
      {
        utensilId: 'ut-38',
        name: 'Termômetro Digital Culinário Tipo Espeto (-50°C a 300°C)',
        category: 'Medição & Precisão',
        requestedQuantity: 2,
        approvedQuantity: 2,
        unit: 'un',
      },
      {
        utensilId: 'ut-19',
        name: 'Jogo de Aros Cortadores Redondos em Inox (12 tamanhos)',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 1,
        approvedQuantity: 1,
        unit: 'cj',
      },
      {
        utensilId: 'ut-20',
        name: 'Maçarico Culinário a Gás com Acendimento Automático',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 1,
        approvedQuantity: 1,
        unit: 'un',
      },
    ],
    notes: 'Por gentileza separar os ovos da mesma data e creme de leite gelado.',
    alterationRequest: {
      id: 'alt-1',
      requestedAt: '2026-09-15 08:45',
      instructorId: 'inst-2',
      classId: 'turma-2',
      type: 'mudanca_sala',
      title: 'Troca de Laboratório para Ateliê Climatizado de Chocolateria',
      reason: 'A aula exige temperatura ambiente controlada a 19°C para cristalização correta da manteiga de cacau e glaçagem espelhada.',
      previousValue: 'Cozinha Pedagógica 02',
      newValue: 'Ateliê de Confeitaria & Chocolateria Climatizado',
      status: 'pendente',
    },
  },
  {
    id: 'req-2',
    code: 'REQ-103',
    classId: 'turma-3',
    instructorId: 'inst-1',
    recipeId: 'rec-1',
    recipeName: 'Croissant Francês Tradicional',
    purpose: 'Oficina de Laminação de Massas Noturna',
    requestDate: '2026-09-14 14:00',
    status: 'enviado',
    reviewedAt: '2026-09-14 15:30',
    dispatchedAt: '2026-09-14 16:45',
    dispatchedBy: 'Almoxarifado Central (Chef Gestor)',
    adminDispatchNotes: 'Verificada a afiação das facas e o estado de higienização das assadeiras perfuradas. Entregar assadeiras e rolos limpos ao almoxarifado até as 22h.',
    items: [
      {
        stockItemId: 'item-1',
        name: 'Farinha de Trigo Especial 00',
        requestedQuantity: 5.0,
        approvedQuantity: 5.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-2',
        name: 'Manteiga Extra Sem Sal 82% Lipídios',
        requestedQuantity: 3.0,
        approvedQuantity: 3.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-6',
        name: 'Leite Integral UHT',
        requestedQuantity: 2.5,
        approvedQuantity: 2.5,
        unit: 'L',
      },
    ],
    utensils: [
      {
        utensilId: 'ut-17',
        name: 'Rolo de Polietileno Antiaderente para Massas 40cm',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 4,
        approvedQuantity: 4,
        unit: 'un',
      },
      {
        utensilId: 'ut-18',
        name: 'Tapete de Silicone Silpat Antiaderente 40x30cm',
        category: 'Confeitaria & Panificação',
        requestedQuantity: 6,
        approvedQuantity: 6,
        unit: 'un',
      },
      {
        utensilId: 'ut-28',
        name: 'Assadeira Perfurada em Alumínio para Forno 60x40cm',
        category: 'Panelas & Formas',
        requestedQuantity: 6,
        approvedQuantity: 6,
        unit: 'un',
      },
    ],
  },
];

export const initialDispatches: DispatchRecord[] = [
  {
    id: 'disp-1',
    code: 'ENV-2026-089',
    requisitionId: 'req-2',
    classId: 'turma-3',
    className: 'Panificação Artesanal & Levain',
    instructorId: 'inst-1',
    instructorName: 'Chef Bernardo Guimarães',
    kitchenRoom: 'Laboratório de Panificação 02',
    dispatchedAt: '2026-09-14 16:45',
    dispatchedBy: 'Gestão de Estoque',
    status: 'entregue',
    notes: 'Entregue na bancada refrigerada do laboratório conforme solicitado.',
    adminDispatchNotes: 'Verificada a afiação das facas e o estado de higienização das assadeiras perfuradas. Entregar assadeiras e rolos limpos ao almoxarifado até as 22h.',
    items: [
      {
        stockItemId: 'item-1',
        name: 'Farinha de Trigo Especial 00',
        quantity: 5.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-2',
        name: 'Manteiga Extra Sem Sal 82% Lipídios',
        quantity: 3.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-6',
        name: 'Leite Integral UHT',
        quantity: 2.5,
        unit: 'L',
      },
    ],
    utensils: [
      {
        utensilId: 'ut-17',
        name: 'Rolo de Polietileno Antiaderente para Massas 40cm',
        quantity: 4,
        unit: 'un',
        category: 'Confeitaria & Panificação',
      },
      {
        utensilId: 'ut-18',
        name: 'Tapete de Silicone Silpat Antiaderente 40x30cm',
        quantity: 6,
        unit: 'un',
        category: 'Confeitaria & Panificação',
      },
      {
        utensilId: 'ut-28',
        name: 'Assadeira Perfurada em Alumínio para Forno 60x40cm',
        quantity: 6,
        unit: 'un',
        category: 'Panelas & Formas',
      },
    ],
  },
  {
    id: 'disp-2',
    code: 'ENV-2026-088',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    dispatchedAt: '2026-09-13 08:20',
    dispatchedBy: 'Gestão de Estoque',
    status: 'entregue',
    notes: 'Envio direto avulso para treino de cortes e salteados.',
    adminDispatchNotes: 'Frigideiras conferidas sem arranhões no teflon. Facas afiadas no dia 12.',
    items: [
      {
        stockItemId: 'item-15',
        name: 'Filé Mignon Bovino Limpo',
        quantity: 4.0,
        unit: 'kg',
      },
      {
        stockItemId: 'item-7',
        name: 'Azeite de Oliva Extra Virgem 0.2%',
        quantity: 1.0,
        unit: 'L',
      },
      {
        stockItemId: 'item-14',
        name: 'Cebola Branca Selecionada',
        quantity: 3.0,
        unit: 'kg',
      },
    ],
    utensils: [
      {
        utensilId: 'ut-1',
        name: 'Faca do Chef 8" em Aço Alemão Forjado',
        quantity: 6,
        unit: 'un',
        category: 'Corte & Facas',
      },
      {
        utensilId: 'ut-9',
        name: 'Kit de Tábuas de Corte Coloridas HACCP (5 cores)',
        quantity: 4,
        unit: 'kit',
        category: 'Apoio, Tábuas & Higiene',
      },
      {
        utensilId: 'ut-24',
        name: 'Frigideira Profissional Antiaderente 28cm Fundo Triplo',
        quantity: 4,
        unit: 'un',
        category: 'Panelas & Formas',
      },
    ],
  },
];

// ----------------------------------------------------
// DIRETRIZES DE CICLOS DE COMPRAS POR TIPO DE INSUMO (REUNIÃO GESTÃO / ALUNOS)
// ----------------------------------------------------
export const procurementCyclesConfig: ProcurementCycleInfo[] = [
  {
    id: 'hortifruti',
    title: 'Hortifrúti',
    periodicityLabel: 'Pedido Semanal',
    ruleExplanation: 'Insumos frescos e altamente perecíveis. O pedido é emitido semanalmente para consumo exclusivo dos 7 dias seguintes da grade de aulas.',
    example: 'Exemplo: Pedido fechado toda sexta-feira para as aulas da semana seguinte.',
    categories: ['Hortifruti'],
    fractionedDelivery: false,
  },
  {
    id: 'frios',
    title: 'Frios & Laticínios',
    periodicityLabel: 'Pedido Mensal',
    ruleExplanation: 'Produtos refrigerados com validade intermediária. Pede-se com 1 mês de antecedência para atender todo o mês subsequente.',
    example: 'Exemplo da Reunião: Início de agosto, pede-se para setembro.',
    categories: ['Laticínios e Frios'],
    fractionedDelivery: false,
  },
  {
    id: 'proteina',
    title: 'Proteína (Carnes & Pescados)',
    periodicityLabel: 'Pedido Trimestral',
    ruleExplanation: 'Carnes nobres, aves e pescados congelados/resfriados. Planejamento trimestral em lote com negociação antecipada junto ao Centro de Distribuição.',
    example: 'Exemplo da Reunião: Início de agosto, pede-se para setembro, outubro e novembro (visão de 3 meses).',
    categories: ['Carnes e Pescados'],
    fractionedDelivery: false,
  },
  {
    id: 'mercearia',
    title: 'Mercearia & Secos',
    periodicityLabel: 'Pedido Semestral (Fracionado)',
    ruleExplanation: 'Itens não-perecíveis, secos, farinhas, óleos e chocolates. Compra planejada para o semestre letivo completo com entregas fracionadas mensais.',
    example: 'Exemplo da Reunião: Pedido semestral com entrega fracionada em parcelas mensais para não sobrecarregar o espaço físico do almoxarifado.',
    categories: [
      'Secos e Farinhas',
      'Óleos e Condimentos',
      'Confeitaria e Chocolates',
      'Bebidas e Líquidos',
      'Descartáveis e Higiene',
    ],
    fractionedDelivery: true,
  },
];

// ----------------------------------------------------
// CALENDÁRIO ACADÊMICO DE AULAS PRÁTICAS & CRONOGRAMA DE CONSUMO
// ----------------------------------------------------
export const initialAcademicCalendar: AcademicLessonSchedule[] = [
  // --- SETEMBRO 2026 (Semana 38: 15/09 a 21/09) ---
  {
    id: 'cal-01',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    classCode: 'TUR-2026-M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-09-17',
    weekNumber: 38,
    recipeId: 'rec-2',
    recipeName: 'Risoto de Cogumelos Paris e Parmigiano Reggiano',
    servingsMultiplier: 1.5, // 18 porções
    ingredients: [
      { stockItemId: 'item-8', name: 'Arroz Carnaroli Especial Risoto', quantity: 1.8, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 2.2, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 0.6, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 0.5, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.3, unit: 'L', category: 'Óleos e Condimentos' },
      { stockItemId: 'item-14', name: 'Cebola Branca Selecionada', quantity: 0.8, unit: 'kg', category: 'Hortifruti' },
    ],
  },
  {
    id: 'cal-02',
    classId: 'turma-2',
    className: 'Pâtisserie & Confeitaria Avançada',
    classCode: 'TUR-2026-T1',
    instructorId: 'inst-2',
    instructorName: 'Chef Helena Vasconcelos',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    date: '2026-09-18',
    weekNumber: 38,
    recipeId: 'rec-3',
    recipeName: 'Entremet de Chocolate Belga 54%',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 2.4, unit: 'kg', category: 'Confeitaria e Chocolates' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 3.0, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 0.8, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 2.0, unit: 'cx', category: 'Laticínios e Frios' },
    ],
  },
  {
    id: 'cal-03',
    classId: 'turma-3',
    className: 'Panificação Artesanal & Levain',
    classCode: 'TUR-2026-N1',
    instructorId: 'inst-1',
    instructorName: 'Chef Bernardo Guimarães',
    kitchenRoom: 'Laboratório de Panificação 02',
    date: '2026-09-20',
    weekNumber: 38,
    recipeId: 'rec-4',
    recipeName: 'Focaccia Genovese com Alecrim & Flor de Sal',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 4.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.7, unit: 'L', category: 'Óleos e Condimentos' },
      { stockItemId: 'item-11', name: 'Fermento Biológico Seco Instantâneo', quantity: 0.08, unit: 'pct', category: 'Secos e Farinhas' },
      { stockItemId: 'item-13', name: 'Flor de Sal Gourmet', quantity: 0.16, unit: 'kg', category: 'Óleos e Condimentos' },
    ],
  },

  // --- SETEMBRO 2026 (Semana 39: 22/09 a 28/09) ---
  {
    id: 'cal-04',
    classId: 'turma-4',
    className: 'Cozinha Italiana & Massas Frescas',
    classCode: 'TUR-2026-M2',
    instructorId: 'inst-4',
    instructorName: 'Chef Larissa Dias',
    kitchenRoom: 'Cozinha Prática 03',
    date: '2026-09-23',
    weekNumber: 39,
    recipeId: 'rec-1',
    recipeName: 'Massas Frescas & Folhados Salgados',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 3.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 2.5, unit: 'cx', category: 'Laticínios e Frios' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 0.8, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 0.6, unit: 'kg', category: 'Laticínios e Frios' },
    ],
  },
  {
    id: 'cal-05',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    classCode: 'TUR-2026-M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-09-25',
    weekNumber: 39,
    recipeId: 'rec-custom-1',
    recipeName: 'Tournedos Rossini com Filé Mignon e Cogumelos',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-15', name: 'Filé Mignon Bovino Limpo', quantity: 5.0, unit: 'kg', category: 'Carnes e Pescados' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 3.0, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.0, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-14', name: 'Cebola Branca Selecionada', quantity: 1.5, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.5, unit: 'L', category: 'Óleos e Condimentos' },
    ],
  },

  // --- OUTUBRO 2026 (Mês 10 - Frios & Proteínas & Mercearia) ---
  {
    id: 'cal-06',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    classCode: 'TUR-2026-M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-10-06',
    weekNumber: 41,
    recipeId: 'rec-custom-2',
    recipeName: 'Medalhões de Filé Mignon ao Molho Poivre e Risoto',
    servingsMultiplier: 2.5,
    ingredients: [
      { stockItemId: 'item-15', name: 'Filé Mignon Bovino Limpo', quantity: 6.5, unit: 'kg', category: 'Carnes e Pescados' },
      { stockItemId: 'item-8', name: 'Arroz Carnaroli Especial Risoto', quantity: 2.5, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 2.0, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.2, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 0.9, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 2.0, unit: 'kg', category: 'Hortifruti' },
    ],
  },
  {
    id: 'cal-07',
    classId: 'turma-2',
    className: 'Pâtisserie & Confeitaria Avançada',
    classCode: 'TUR-2026-T1',
    instructorId: 'inst-2',
    instructorName: 'Chef Helena Vasconcelos',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    date: '2026-10-14',
    weekNumber: 42,
    recipeId: 'rec-custom-3',
    recipeName: 'Bombons Trufados e Esculturas de Chocolate',
    servingsMultiplier: 3.0,
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 5.0, unit: 'kg', category: 'Confeitaria e Chocolates' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 4.0, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.5, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 2.0, unit: 'kg', category: 'Secos e Farinhas' },
    ],
  },
  {
    id: 'cal-08',
    classId: 'turma-3',
    className: 'Panificação Artesanal & Levain',
    classCode: 'TUR-2026-N1',
    instructorId: 'inst-1',
    instructorName: 'Chef Bernardo Guimarães',
    kitchenRoom: 'Laboratório de Panificação 02',
    date: '2026-10-21',
    weekNumber: 43,
    recipeId: 'rec-1',
    recipeName: 'Croissants & Viennoiserie Folhada Clássica',
    servingsMultiplier: 3.0,
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 6.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 3.5, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-6', name: 'Leite Integral UHT', quantity: 3.0, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 1.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 2.0, unit: 'cx', category: 'Laticínios e Frios' },
      { stockItemId: 'item-11', name: 'Fermento Biológico Seco Instantâneo', quantity: 0.15, unit: 'pct', category: 'Secos e Farinhas' },
    ],
  },
  {
    id: 'cal-09',
    classId: 'turma-4',
    className: 'Cozinha Italiana & Massas Frescas',
    classCode: 'TUR-2026-M2',
    instructorId: 'inst-4',
    instructorName: 'Chef Larissa Dias',
    kitchenRoom: 'Cozinha Prática 03',
    date: '2026-10-28',
    weekNumber: 44,
    recipeId: 'rec-custom-4',
    recipeName: 'Ravioli de Cogumelos e Parmesão na Manteiga de Sálvia',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 3.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 3.5, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 1.2, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.0, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 2.0, unit: 'cx', category: 'Laticínios e Frios' },
    ],
  },

  // --- NOVEMBRO 2026 (Mês 11 - Proteína Trimestral & Frios & Mercearia) ---
  {
    id: 'cal-10',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    classCode: 'TUR-2026-M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-11-10',
    weekNumber: 46,
    recipeId: 'rec-custom-5',
    recipeName: 'Chateaubriand com Cogumelos Salteados e Redução',
    servingsMultiplier: 2.5,
    ingredients: [
      { stockItemId: 'item-15', name: 'Filé Mignon Bovino Limpo', quantity: 7.0, unit: 'kg', category: 'Carnes e Pescados' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 3.0, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.2, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 0.6, unit: 'L', category: 'Óleos e Condimentos' },
      { stockItemId: 'item-14', name: 'Cebola Branca Selecionada', quantity: 2.0, unit: 'kg', category: 'Hortifruti' },
    ],
  },
  {
    id: 'cal-11',
    classId: 'turma-2',
    className: 'Pâtisserie & Confeitaria Avançada',
    classCode: 'TUR-2026-T1',
    instructorId: 'inst-2',
    instructorName: 'Chef Helena Vasconcelos',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    date: '2026-11-18',
    weekNumber: 47,
    recipeId: 'rec-custom-6',
    recipeName: 'Tortas Finas de Chocolate e Mousse de Frutas',
    servingsMultiplier: 2.5,
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 4.5, unit: 'kg', category: 'Confeitaria e Chocolates' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 3.5, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 2.5, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 2.0, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 1.8, unit: 'kg', category: 'Secos e Farinhas' },
    ],
  },
  {
    id: 'cal-12',
    classId: 'turma-3',
    className: 'Panificação Artesanal & Levain',
    classCode: 'TUR-2026-N1',
    instructorId: 'inst-1',
    instructorName: 'Chef Bernardo Guimarães',
    kitchenRoom: 'Laboratório de Panificação 02',
    date: '2026-11-25',
    weekNumber: 48,
    recipeId: 'rec-4',
    recipeName: 'Pães de Fermentação Longa e Focaccias Aromáticas',
    servingsMultiplier: 3.0,
    ingredients: [
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 8.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 1.2, unit: 'L', category: 'Óleos e Condimentos' },
      { stockItemId: 'item-13', name: 'Flor de Sal Gourmet', quantity: 0.25, unit: 'kg', category: 'Óleos e Condimentos' },
      { stockItemId: 'item-11', name: 'Fermento Biológico Seco Instantâneo', quantity: 0.12, unit: 'pct', category: 'Secos e Farinhas' },
    ],
  },

  // --- DEZEMBRO 2026 (Mês 12 - Conclusão do Semestre 2026.2) ---
  {
    id: 'cal-13',
    classId: 'turma-1',
    className: 'Gastronomia Profissional M1',
    classCode: 'TUR-2026-M1',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-12-08',
    weekNumber: 50,
    recipeId: 'rec-2',
    recipeName: 'Banquete de Encerramento - Risotos e Carnes Nobres',
    servingsMultiplier: 3.5,
    ingredients: [
      { stockItemId: 'item-15', name: 'Filé Mignon Bovino Limpo', quantity: 8.0, unit: 'kg', category: 'Carnes e Pescados' },
      { stockItemId: 'item-8', name: 'Arroz Carnaroli Especial Risoto', quantity: 4.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-10', name: 'Cogumelos Paris Frescos', quantity: 4.0, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 1.5, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 2.0, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-7', name: 'Azeite de Oliva Extra Virgem 0.2%', quantity: 1.0, unit: 'L', category: 'Óleos e Condimentos' },
    ],
  },
  {
    id: 'cal-14',
    classId: 'turma-2',
    className: 'Pâtisserie & Confeitaria Avançada',
    classCode: 'TUR-2026-T1',
    instructorId: 'inst-2',
    instructorName: 'Chef Helena Vasconcelos',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    date: '2026-12-10',
    weekNumber: 50,
    recipeId: 'rec-3',
    recipeName: 'Mostra Gastronômica - Grand Entremets e Chocolates Nobres',
    servingsMultiplier: 3.5,
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 6.0, unit: 'kg', category: 'Confeitaria e Chocolates' },
      { stockItemId: 'item-12', name: 'Creme de Leite Fresco Pasteurizado 35%', quantity: 5.0, unit: 'L', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 2.5, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-4', name: 'Ovos Caipiras Grandes (Dúzia)', quantity: 3.5, unit: 'cx', category: 'Laticínios e Frios' },
    ],
  },

  // --- HISTÓRICO: 1º SEMESTRE 2026 (Para teste de relatórios de Turmas Inativas / Concluídas) ---
  {
    id: 'cal-hist-01',
    classId: 'turma-5',
    className: 'Técnicas Básicas de Cocção & Habilidades de Faca (2026.1)',
    classCode: 'TUR-2026-N0',
    instructorId: 'inst-3',
    instructorName: 'Chef Rodrigo Martins',
    kitchenRoom: 'Cozinha Pedagógica Principal 01',
    date: '2026-06-15',
    weekNumber: 24,
    recipeId: 'rec-2',
    recipeName: 'Risoto de Legumes e Cortes Clássicos (Aula Concluída)',
    servingsMultiplier: 2.0,
    ingredients: [
      { stockItemId: 'item-8', name: 'Arroz Carnaroli Especial Risoto', quantity: 2.5, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-14', name: 'Cebola Branca Selecionada', quantity: 2.0, unit: 'kg', category: 'Hortifruti' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 0.8, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-9', name: 'Queijo Parmigiano Reggiano D.O.P.', quantity: 0.6, unit: 'kg', category: 'Laticínios e Frios' },
    ],
  },
  {
    id: 'cal-hist-02',
    classId: 'turma-6',
    className: 'Fundamentos de Confeitaria Clássica (2026.1)',
    classCode: 'TUR-2026-T0',
    instructorId: 'inst-2',
    instructorName: 'Chef Helena Vasconcelos',
    kitchenRoom: 'Ateliê de Confeitaria Climatizado',
    date: '2026-06-20',
    weekNumber: 25,
    recipeId: 'rec-3',
    recipeName: 'Fundamentos de Ganache e Massas Quebradiças (Aula Concluída)',
    servingsMultiplier: 1.5,
    ingredients: [
      { stockItemId: 'item-5', name: 'Chocolate Nobre Meio Amargo 54% Callebaut', quantity: 2.0, unit: 'kg', category: 'Confeitaria e Chocolates' },
      { stockItemId: 'item-1', name: 'Farinha de Trigo Especial 00', quantity: 2.0, unit: 'kg', category: 'Secos e Farinhas' },
      { stockItemId: 'item-2', name: 'Manteiga Extra Sem Sal 82% Lipídios', quantity: 1.2, unit: 'kg', category: 'Laticínios e Frios' },
      { stockItemId: 'item-3', name: 'Açúcar Cristal Refinado', quantity: 1.0, unit: 'kg', category: 'Secos e Farinhas' },
    ],
  },
];

